# Generated by Django 2.2.1 on 2019-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191009_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
